name: wrlc
recipe: drupal7
config:
  webroot: docroot
  php: '7.0'
  database: mariadb:10.1
proxy:
  appserver:
    - wrlc.lndo.site
    - hq.wrlc.lndo.site
    - libraries.wrlc.lndo.site
services:
  hq:
    type: mariadb:10.1
    portforward: true
  libraries:
    type: mariadb:10.1
    portforward: true
